CONSTRUCTION_SAFETY_PROMPTS = [
    # Scenario 1: Distracted Worker Under Scaffold (EARLY DETECTION)
    (
        "Wide establishing shot from elevated surveillance camera angle showing active construction "
        "site ground level and scaffolding two stories above. Scene begins with normal workflow - "
        "several workers moving materials, one operating equipment. Camera positioned to capture "
        "vertical height and horizontal breadth simultaneously. Focus develops on one worker in orange "
        "safety vest who stops in walking path directly under scaffold structure and pulls out mobile "
        "phone, begins texting with head down. Camera clearly shows DETECTABLE RISK FACTORS: worker "
        "stationary in falling object zone marked by yellow caution striping on ground, worker's "
        "attention completely on phone screen not surroundings, unsecured red tool bag visible on "
        "scaffold platform edge above beginning to slide toward edge, no overhead protection or "
        "catch nets present, other workers in motion but not watching this area. Hold on this moment "
        "of escalating risk - tool bag teetering on edge 20 feet above distracted worker. All warning "
        "signs present and detectable before impact. Wide enough to show spatial relationships, danger "
        "zones, and multiple unsafe conditions. Overcast natural light, industrial construction site, "
        "realistic multi-level workspace with clear sight lines for AI detection training."
    ),
    # Scenario 2: Improper Ladder Safety (EARLY DETECTION)
    (
        "Wide angle shot from across street level showing entire construction building facade from "
        "ground to three stories up, full width to capture context. Camera positioned like fixed "
        "surveillance camera capturing whole work area. Scene opens with metal extension ladder already "
        "leaning against building at visibly incorrect steep angle. Camera clearly shows DETECTABLE "
        "HAZARDS before climbing begins: ladder angle approximately 80 degrees (should be 75 degrees or "
        "less), base of ladder has no visible foot pads stabilizers or ground anchoring, top of ladder "
        "not secured tied-off or braced against structure, ladder extends only 2 feet above landing "
        "(should extend 3+ feet), no second worker spotter present in area, no safety cones or barrier "
        "tape around ladder base, nearby workers walking past unaware. Worker in blue coveralls approaches "
        "ladder carrying power drill in one hand and heavy tool belt. Worker begins climb showing ADDITIONAL "
        "RISK FACTORS: improper three-point contact (using only two limbs), body leaning laterally outside "
        "ladder rails instead of centered, tools unclipped hanging free creating imbalance, each step causes "
        "visible ladder flex and base movement on ground. Pause on worker at mid-height showing all detectable "
        "violations - improper setup, improper technique, multiple intervention opportunities. Wide perspective "
        "shows ground securing issues and height hazard simultaneously. Bright natural daylight, other "
        "construction activity in background, realistic ladder installation showing all setup deficiencies."
    ),
    # Scenario 3: Missing PPE - Power Tool Operation (EARLY DETECTION)
    (
        "Medium-wide shot of workshop workbench area from angle showing worker's full body profile "
        "face and surrounding workspace. Camera positioned at torso height 10 feet away capturing "
        "worker and visible safety equipment storage in background. Scene begins with worker in gray "
        "work shirt and hard hat approaching workbench where angle grinder and metal beam are set up. "
        "Camera emphasizes DETECTABLE PPE VIOLATIONS visible before work begins: worker wearing hard hat "
        "but NO safety goggles or face shield on face, NO goggles hanging around neck or clipped to vest, "
        "NO hearing protection ear muffs or plugs visible, work gloves present but shirt sleeves rolled "
        "up exposing forearms, NO protective apron for metal grinding work. Background shows SAFETY "
        "RESOURCES AVAILABLE: PPE cabinet with safety glasses visible on wall 15 feet away, eye wash "
        "station marked with green sign, safety compliance poster showing proper PPE for grinding operations, "
        "unused face shield hanging on peg. Worker picks up angle grinder checks power cord and positions "
        "tool against metal beam with finger near trigger ready to start. Hold this preparation moment "
        "showing clear PPE deficiency detectable before operation begins - intervention point. Metal shavings "
        "and grinding marks on beam indicate this is repeat work with spark generation potential. Worker's "
        "unprotected face oriented toward grinding point. Shot wide enough to show missing PPE, available "
        "safety equipment, and work about to commence. Indoor workshop, bright fluorescent overhead lighting, "
        "safety compliance materials visible emphasizing preventable violation."
    ),
    # Scenario 4: Unsecured Scaffold Platform (EARLY DETECTION)
    (
        "Wide shot from ground level angled up showing complete multi-level tubular metal scaffolding "
        "structure from ground to third floor - full system visible. Camera positioned to capture "
        "vertical spans, platform levels, and ground clearance simultaneously like job site safety "
        "inspection view. Scene opens on two workers in high-vis vests already present on second-floor "
        "scaffold platform preparing to move materials. Camera emphasizes DETECTABLE STRUCTURAL HAZARDS: "
        "visible 8-inch gap between wooden planks on platform where one end bracket is missing, unsecured "
        "plank end cantilevered beyond support with no tie-down clamp visible, platform lacks perimeter "
        "guardrails or toe boards, vertical lifeline anchor points present on scaffold but workers' safety "
        "harness lanyards visibly dangling unconnected, base plates at ground level show missing mud sills "
        "under some legs, diagonal bracing incomplete on one section, tools and materials stacked near "
        "unsecured plank creating additional edge loading. Workers begin walking across platform toward "
        "the problem plank area - trajectory clear. Hold before worker reaches unstable section showing "
        "multiple detectable fall hazards: unconnected harnesses, gap in decking, inadequate edge protection, "
        "problematic weight distribution. Camera wide enough to show 15-foot fall distance to ground below, "
        "improperly secured components at multiple levels, and worker paths toward danger zone. All structural "
        "deficiencies visible and detectable for intervention before worker reaches hazard. Daytime exterior, "
        "building under construction in background, clear sight lines showing scaffold integrity issues and "
        "PPE non-compliance simultaneously."
    ),
    # Scenario 5: Forklift Blind Spot Collision Path (EARLY DETECTION)
    (
        "Wide aerial overhead shot of warehouse loading dock showing entire operational area like bird's-eye "
        "surveillance camera view. Camera positioned high enough to see forklift, pedestrian walkways, "
        "loading zones, and traffic patterns simultaneously. Scene opens with yellow forklift with stacked "
        "pallets positioned at loading dock, engine running brake lights on, preparing to reverse into "
        "staging area. Camera shows DETECTABLE SAFETY DEFICIENCIES: no ground guide spotter person present "
        "near forklift, no painted pedestrian walkway lanes or vehicle separation barriers, no floor-mounted "
        "convex mirrors at blind spot intersections, backup alarm light flashing on forklift roof but no "
        "visible audible warning system, driver in orange vest visible through forklift cage checking only "
        "right side mirror not full 360-degree scan. Simultaneously show pedestrian worker in blue hard hat "
        "and reflective vest walking across warehouse floor from left side on collision course with forklift's "
        "reverse path - pedestrian wearing headphones visible as white earbuds, looking down at tablet or "
        "clipboard, not watching forklift. Camera emphasizes CONVERGENCE OF RISK FACTORS detectable now: "
        "forklift begins slow reverse motion, pedestrian continues steady walking pace from blind spot "
        "zone, intersection point calculable, no safety barriers or warning systems between them, no other "
        "workers in immediate area noticing the developing situation. Hold this moment showing both parties "
        "on collision trajectory with 15-20 feet separation - detection and intervention window clearly "
        "present. Overhead view shows spatial relationships, movement vectors, blind zones, and lack of "
        "safety controls. Industrial warehouse setting with concrete floor, stacked pallet rows, bright "
        "natural light from large bay doors, wide enough perspective to see entire developing scenario "
        "before critical moment."
    ),
    # Scenario 6: Frayed Power Cable Near Water Puddle (EARLY DETECTION)
    (
        "Wide angle ground-level shot from fixed surveillance camera showing construction site break "
        "area and adjacent work zone. Camera positioned to capture 30-foot radius showing concrete slab "
        "with visible water puddle from morning rain, temporary power distribution setup, and worker "
        "break table. Scene opens with DETECTABLE HAZARD ALREADY PRESENT: orange heavy-duty extension "
        "cord running across ground from generator to power tools, visible outer insulation damage and "
        "fraying at mid-point exposing copper wiring beneath, damaged section positioned 3 feet from "
        "edge of water puddle approximately 6 inches deep. Camera shows RISK INDICATORS: no ground fault "
        "circuit interrupter (GFCI) visible on power cord, no cord elevation or protection crossing "
        "walkway, no caution cones or barrier tape around puddle or damaged cord, electrical hazard "
        "warning signs absent. Worker in yellow vest finishes break at table and begins walking toward "
        "active work area following natural foot traffic path directly toward puddle and damaged cord "
        "zone. BEFORE moment clearly shows: worker trajectory toward hazard zone, wet boots visible from "
        "previous work, damaged cord energized (small tool running in background creating slight cord "
        "vibration), standing water creating conductive path. Hold frame showing worker 10 feet from "
        "hazard with clear intervention window. Wide shot captures spatial relationships between power "
        "source, damaged section, water hazard, and approaching worker. Natural overcast lighting, wet "
        "surfaces with visible reflections, realistic construction site power setup showing multiple "
        "detectable electrical safety violations before contact."
    ),
    # Scenario 7: Unsupported Trench Wall Collapse Warning (EARLY DETECTION)
    (
        "Elevated wide shot from site supervisor position showing excavation area from 20 feet away "
        "capturing full trench length of 40 feet and 8-foot depth. Camera angle shows trench profile, "
        "ground surface, and surrounding work area simultaneously like standard construction site "
        "monitoring. Scene opens revealing DETECTABLE STRUCTURAL HAZARDS: excavated trench with vertical "
        "walls in clay soil showing no shoring, shielding, or sloping systems installed, visible "
        "horizontal crack developing along trench wall at 4-foot depth extending 15 feet, small soil "
        "chunks already fallen to trench bottom indicating wall instability, puddles at bottom showing "
        "groundwater seepage weakening soil, excavated soil pile positioned only 3 feet from trench edge "
        "creating surcharge load. Camera clearly shows BEFORE WARNING SIGNS: worker in hard hat and "
        "orange vest at ground level preparing to descend ladder into trench carrying pipe sections, "
        "ladder angle proper but positioned against unstable wall section with visible cracking, no "
        "trench box or protective system visible anywhere in frame, no second worker acting as spotter "
        "or safety monitor at surface, competent person inspection checklist clipboard visible on ground "
        "but no one actively monitoring. Worker places foot on first ladder rung beginning descent while "
        "camera shows soil along crack line beginning to separate and small pebbles trickling down wall "
        "face. Hold this critical moment: worker committed to entering unprotected trench, visible soil "
        "failure indicators present, structural collapse imminent, clear intervention opportunity before "
        "entry. Wide perspective captures trench depth, wall condition, inadequate protective systems, "
        "and worker position. Natural daylight, excavation site, realistic soil conditions showing "
        "detectable pre-collapse indicators for AI training."
    ),
    # Scenario 8: Crane Load Swing Into Occupied Zone (EARLY DETECTION)
    (
        "Wide aerial shot from elevated camera position showing construction site from bird's-eye view "
        "capturing mobile crane, work zones, and personnel movement across 100-foot area. Camera mounted "
        "like tower crane operator view or high surveillance position showing spatial relationships. "
        "Scene opens with yellow mobile crane with extended boom lifting steel beam load suspended 30 "
        "feet in air. Camera reveals DETECTABLE SAFETY VIOLATIONS BEFORE INCIDENT: load suspended but "
        "not fully secured with multiple tag lines visible but only one being held by ground worker, "
        "crane beginning slow swing rotation to position beam toward staging area, load swing path "
        "crosses directly over occupied work zone where three workers in hard hats are actively working "
        "at ground level installing rebar framework, no physical barriers or warning tape isolating "
        "workers beneath swing path, no dedicated spotter watching load path and signaling workers, no "
        "audible warning horn or visual warning lights activated on crane. BEFORE indicators clearly "
        "visible: workers below completely focused on rebar work not watching overhead load, suspended "
        "beam (3000+ lbs visible weight) accelerating in swing arc due to crane rotation, single tag "
        "line inadequate as load begins to pendulum swing outside controlled path, wind sock on nearby "
        "pole showing 15+ mph wind adding load movement. Freeze moment when load is mid-swing trajectory "
        "with workers still 8 feet from direct impact point - intervention window present. Camera shows "
        "converging danger: load path, worker positions, insufficient controls, environmental factors. "
        "Wide overhead view captures full lift operation site, movement vectors, and exclusion zone "
        "violations. Bright daylight, active construction site, multiple detectable rigging and "
        "communication failures before hazardous load reaches workers."
    ),
    # Scenario 9: Unstable Material Stack Toppling (EARLY DETECTION)
    (
        "Medium-wide ground level shot from warehouse dock camera view showing outdoor material storage "
        "area with concrete pad and stacked construction materials. Camera positioned 40 feet away "
        "capturing full view of storage zone, loading area, and foot traffic paths like fixed "
        "surveillance monitoring. Scene reveals DETECTABLE STORAGE VIOLATIONS: wooden pallets stacked "
        "vertically six units high (over 8 feet) without banding or strapping visible, stack leaning "
        "approximately 10 degrees off vertical toward main walkway, ground surface visibly uneven with "
        "settling causing lean, no anti-toppling devices or wall bracing, faded warning placards about "
        "stack height limits posted on fence but clearly violated, forklift tire marks showing recent "
        "unstable placement. Adjacent to leaning stack shows ADDITIONAL HAZARDS: bundle of steel rebar "
        "leaning against pallet base adding lateral load, no safety setback distance from pedestrian "
        "path (walkway only 4 feet from stack base), delivery truck backing into loading zone creating "
        "ground vibration. Camera captures BEFORE INCIDENT MOMENT: worker in blue coveralls and yellow "
        "vest walking along designated path carrying tablet and water bottle approaching unstable stack "
        "zone, worker's attention on tablet screen not surroundings, leaning stack shows visible "
        "increased tilt as truck backs over uneven ground sending vibrations, top pallet boards starting "
        "to slide forward past base pallet footprint, gap opening between stacked units. Hold frame with "
        "worker 12 feet from impact zone, stack visibly becoming more unstable, clear warning signs "
        "present - intervention opportunity exists. Wide shot shows material storage violations, "
        "environmental factors, and approaching personnel. Natural daylight, construction supply yard, "
        "realistic material stacking showing multiple detectable collapse precursors before failure."
    ),
    # Scenario 10: Unsecured Formwork Concrete Blowout (EARLY DETECTION)
    (
        "Wide shot from 25 feet away at ground level showing concrete wall formwork panel system on "
        "construction site. Camera angle captures full 12-foot height of formwork, surrounding work "
        "area, and concrete pump truck like standard site documentation camera. Scene opens on vertical "
        "formwork with DETECTABLE STRUCTURAL DEFICIENCIES BEFORE POUR: plywood panel form showing visible "
        "bow or bulge outward at mid-height indicating inadequate bracing, tie rod spacing visibly "
        "irregular with missing tie rods at bulge location (gaps of 4 feet instead of specified 2 feet), "
        "vertical walers not properly aligned with gaps visible, diagonal kicker braces at base only on "
        "one side instead of both, formwork stakes driven into soft soil showing recent rain saturation, "
        "no form inspection approval tags visible. Camera shows BEFORE HAZARD ESCALATION: concrete pump "
        "truck positioned with boom extended to top of form, pump operator in orange vest signals ready, "
        "two workers in hard hats stand at base of form on the bulging side preparing to monitor pour, "
        "concrete discharge hose at top of form beginning flow with wet concrete visible starting to "
        "fill cavity. EARLY WARNING SIGNS VISIBLE: bulge in panel increases slightly as first concrete "
        "flows behind form adding pressure, small concrete leak appears at bottom form joint indicating "
        "seal failure, workers notice leak and look up at bulging section but remain in position instead "
        "of moving to safe distance, no laser level or plumb monitoring equipment in use, engineered "
        "pour rate calculations clipboard sitting unused on nearby tool cart. Hold moment as concrete "
        "level rises to 3-foot depth behind compromised form section - workers still in potential "
        "blowout zone, structural inadequacy clear, intervention window present before catastrophic "
        "failure. Wide shot captures formwork deficiencies, concrete placement operation, worker "
        "positions, and developing pressure situation. Daylight construction site, active concrete pour "
        "showing detectable formwork failures before blowout."
    ),
    # Scenario 11: Roofing Work Near Unprotected Edge (EARLY DETECTION)
    (
        "Wide elevated shot from aerial work platform or adjacent building showing flat commercial roof "
        "from 30-foot distance capturing full roof perimeter, work area, and ground below. Camera "
        "positioned like safety monitor overview showing roof edges and interior simultaneously. Scene "
        "opens revealing FALL PROTECTION VIOLATIONS: flat roof with no perimeter guardrail system "
        "installed, no warning line system visible at required 6-foot setback from edge, no safety "
        "monitoring system in place, roofing materials and tools scattered within 4 feet of unprotected "
        "roof edge. Camera clearly shows DETECTABLE BEFORE HAZARDS: two workers in hard hats and safety "
        "vests (but no visible harnesses or lanyards) actively installing roofing membrane, work area "
        "gradually moving toward roof edge as installation progresses, one worker walking backward while "
        "pulling membrane roll not watching direction relative to edge now only 8 feet behind, second "
        "worker using heat gun focused on seam work positioned sideways to edge, wind picking up shown "
        "by loose membrane edges flapping and nearby flag on building showing 20+ mph gusts, no roof "
        "edge visual markers like flags or cones, no safety monitor or competent person watching from "
        "elevated position. CRITICAL MOMENT CAPTURED: worker walking backward with membrane takes another "
        "step reducing edge distance to 5 feet while looking down at material not behind, membrane roll "
        "requires three more backward steps to complete current section - trajectory toward edge clear, "
        "second worker's heat gun power cord stretches across first worker's path creating trip hazard "
        "that would send backward-moving worker toward edge, wind gust causes worker to adjust balance. "
        "Hold frame showing converging hazards before edge reached - intervention opportunity exists. "
        "Wide shot captures roof perimeter, edge proximity, inadequate fall protection, environmental "
        "factors, and worker positions/trajectories. Natural daylight, commercial roofing site, clear "
        "30-foot fall hazard with multiple detectable violations before incident."
    ),
    # Scenario 12: Welding Near Flammable Materials (EARLY DETECTION)
    (
        "Medium-wide shot from fixed shop camera angle showing interior fabrication workshop area. "
        "Camera positioned 35 feet away capturing welding station, surrounding storage, and ventilation "
        "systems like standard facility monitoring. Scene reveals FIRE SAFETY VIOLATIONS BEFORE WORK: "
        "welding bay with metal workbench and welding machine setup, worker in leather welding jacket "
        "preparing acetylene cutting torch visible by gas regulators and hose configuration, hot work "
        "permit clipboard hanging on wall but no visible completed inspection checklist, welding curtain "
        "on right side only leaving left exposure open. Camera shows DETECTABLE HAZARDS IN FRAME: "
        "wooden shipping pallets stacked only 8 feet from welding area (required clearance 35 feet), "
        "cardboard boxes containing packaging materials on pallets with visible flammable warning labels, "
        "plastic sheeting draped over nearby equipment within 12 feet of welding zone, aerosol spray "
        "paint cans on shelf above workbench in direct spark exposure zone, oil-soaked rags visible in "
        "open container instead of closed metal safety can, no fire extinguisher visible in immediate "
        "area, no fire watch person present, no welding screens providing full spark containment. "
        "BEFORE HOT WORK MOMENT: welder adjusts regulators and opens acetylene valve (audible hiss), "
        "striker tool in hand preparing to ignite torch, welder's attention focused on torch tip and "
        "workpiece not surroundings, slight breeze from open bay door causing plastic sheeting to flutter "
        "closer to work area, concrete floor shows metal grinding debris but also scattered sawdust from "
        "earlier work creating fine fuel. Freeze moment with torch ready to ignite, multiple ignition "
        "sources within spark travel radius, inadequate clearances documented, intervention point before "
        "hot work begins. Wide shot captures welding setup, flammable material positions, clearance "
        "violations, and missing fire prevention controls. Industrial lighting, fabrication shop, "
        "realistic hot work area showing multiple detectable fire hazards before ignition."
    ),
    # Scenario 13: Excavator Backing Into Blind Spot Worker (EARLY DETECTION)
    (
        "Wide overhead shot from elevated site office window showing excavation work area and equipment "
        "movement zone. Camera captures 80-foot operational radius showing excavator, material piles, "
        "and walking paths like standard construction site surveillance. Scene opens with yellow tracked "
        "excavator completing trench digging and beginning to reposition by rotating and backing toward "
        "spoil pile staging area. Camera reveals DETECTABLE SAFETY DEFICIENCIES: no ground guide spotter "
        "walking with equipment providing signals, no high-visibility exclusion zone barriers around "
        "heavy equipment operation area, excavator backup alarm light flashing on cab roof but equipment "
        "operator only checking right side mirror showing limited rearward visibility, job site shows "
        "pedestrian foot traffic paths crossing equipment movement zones without grade separation or "
        "timing controls. CONVERGENCE OF HAZARDS VISIBLE: worker in orange vest and white hard hat "
        "walking from material storage area along unofficial path toward portable toilet facilities, "
        "worker's trajectory intersects excavator's backing path at blind spot directly behind machine "
        "cab and counterweight, worker wearing ear protection (visible earmuffs) blocking hearing of "
        "backup alarms, worker's attention on mobile phone checking time or messages not watching for "
        "equipment, excavator begins backward motion at slow travel speed (tracks turning). Camera shows "
        "EARLY WARNING INDICATORS: separation distance 40 feet and closing, worker and excavator movement "
        "vectors converging toward intersection point in 8-10 seconds, no other workers in area noticing "
        "situation, operator's mirror view blocked by excavator's counterweight exactly where worker is "
        "approaching, ground conditions dusty reducing overall visibility. Hold frame showing calculated "
        "collision trajectory with time for intervention - worker 25 feet from impact point, excavator "
        "backing speed steady, multiple opportunities to alert either party. Overhead wide shot captures "
        "full movement vectors, blind zones, and absence of traffic controls. Natural daylight, active "
        "excavation site, realistic heavy equipment operation showing detectable collision precursors."
    ),
    # Scenario 14: Confined Space Entry Without Monitoring (EARLY DETECTION)
    (
        "Wide angle shot from ground level 30 feet away showing industrial tank farm area with large "
        "cylindrical storage tanks and maintenance access points. Camera positioned to capture tank "
        "base, entry manway, surrounding equipment, and worker positions like facility safety camera. "
        "Scene opens on 20-foot diameter storage tank with DETECTABLE CONFINED SPACE VIOLATIONS: "
        "circular manway hatch at ground level standing completely open (24-inch opening), no confined "
        "space entry permit holder posted at entrance or attached to nearby fence, no atmospheric "
        "monitoring equipment visible at entry point or in area, no ventilation blower or fresh air "
        "supply system set up at opening, no safety harness retrieval tripod erected over opening, no "
        "attendant or safety watch person stationed at entrance. Camera shows BEFORE ENTRY HAZARDS: "
        "single worker in blue coveralls and yellow hard hat approaches open manway carrying flashlight "
        "and adjustable wrench, no personal atmospheric monitor clipped to worker's vest or belt, no "
        "supplied air respirator or SCBA equipment visible, no communication radio or lifeline rope "
        "attached to worker, no second person anywhere in frame to serve as attendant, worker conducts "
        "no atmospheric testing before entry. CRITICAL WARNING SIGNS: faded H2S warning placard on tank "
        "exterior indicating hydrogen sulfide hazard history, rust staining around manway suggesting "
        "moisture and potential oxygen-deficient atmosphere, valve lineup chart shows tank last contained "
        "petroleum product requiring 24-hour ventilation before entry, wind sock hanging limp indicating "
        "no natural ventilation, worker bends down and peers into dark opening shining flashlight inside "
        "preparing to climb in. Freeze moment with worker at manway threshold beginning descent - "
        "intervention window clear before entering hazardous atmosphere. Wide shot captures tank entry "
        "point, complete absence of required safety controls, solo worker, and equipment deficiencies. "
        "Industrial tank farm, natural overcast light, realistic confined space showing multiple permit "
        "and monitoring violations detectable before entry."
    ),
    # Scenario 15: Chemical Container Leak Near Drain (EARLY DETECTION)
    (
        "Medium-wide shot from elevated warehouse corner camera showing chemical storage area and floor "
        "drain system. Camera angle captures 40-foot zone including storage racks, walking aisles, and "
        "drainage points like standard facility monitoring. Scene reveals ENVIRONMENTAL HAZARD IN "
        "PROGRESS: secondary containment pallet holding four 55-gallon drums with visible hazmat labels, "
        "front right drum showing wet streak down side indicating active leak from corroded bung, small "
        "puddle of clear liquid collecting in pallet sump but liquid level approaching overflow capacity, "
        "camera clearly shows liquid beginning to drip over pallet edge onto concrete floor, floor drain "
        "opening positioned only 6 feet from pallet with visible slope directing liquid flow toward "
        "drain. Camera captures DETECTABLE VIOLATIONS: no spill containment boom or absorbent materials "
        "deployed around leak, no caution tape or barriers preventing access to area, drum labels show "
        "corrosive chemical classification but no corresponding spill kit visible in required 25-foot "
        "radius, safety data sheets (SDS) binder visible on wall 30 feet away but no emergency reference "
        "at storage location, chemical inventory log clipboard shows last inspection date 45 days prior "
        "(required weekly), no vapor monitoring in area despite chemical's volatile nature. BEFORE "
        "ESCALATION MOMENT: worker in brown uniform and face shield approaches from adjacent aisle "
        "carrying clipboard for routine inventory check, worker's path leads directly toward leaking "
        "drums with liquid now forming stream toward drain, worker not yet aware of spill situation "
        "focused on clipboard, small vapor cloud visible rising from leaked chemical puddle indicating "
        "evaporation, floor shows liquid spreading in 3-foot radius and advancing toward worker's "
        "approach path creating slip hazard. Hold frame showing worker 15 feet from contact with "
        "contaminated area - intervention opportunity before exposure to chemical or vapor inhalation. "
        "Wide shot shows leak source, containment failure, spreading contamination, drain system risk, "
        "and approaching personnel. Industrial warehouse, fluorescent lighting, realistic chemical "
        "storage showing detectable spill and multiple response failures before human exposure."
    ),
    # Scenario 16: High Wind Unsecured Material Lift (EARLY DETECTION)
    (
        "Wide shot from ground level 40 feet away showing construction site tower and material hoist "
        "system. Camera positioned to capture ground loading area, vertical hoist path to third floor, "
        "and weather conditions like site safety documentation view. Scene opens with DETECTABLE HAZARDS "
        "BEFORE LIFT: external construction hoist platform at ground level loaded with stack of plywood "
        "sheets (20+ sheets visible 4x8 foot size), plywood stack secured only with single ratchet strap "
        "across middle - no secondary strapping at top or bottom, load extends 8 inches beyond platform "
        "edge on one side, hoist operator in enclosed cab preparing to activate lift controls, wind sock "
        "on nearby building showing strong consistent horizontal position indicating 25+ mph sustained "
        "winds, loose debris visible blowing across ground - plastic sheeting, paper, small boards "
        "tumbling past. Camera shows ENVIRONMENTAL AND PROCEDURAL VIOLATIONS: no wind speed anemometer "
        "reading documented on lift operator's daily log (required measurement), lift manufacturer "
        "placard visible on hoist frame stating maximum wind speed 20 mph for operation, American flag "
        "on building fully extended and whipping showing gusts exceeding limits, no spotter positioned at "
        "third floor landing to receive load, workers on third floor visible but focused on other tasks "
        "not watching hoist approach, tarps on adjacent scaffolding flapping violently showing wind "
        "strength. CRITICAL MOMENT: operator activates hoist and platform begins ascending, platform "
        "rises 5 feet and plywood sheets immediately catch wind with visible flexing and movement against "
        "insufficient restraint, top sheets beginning to lift up at unsecured corner, strap shows "
        "tension but load shifting on platform. Hold frame at 8 feet elevation with sheets becoming "
        "unstable, platform continuing upward, workers below in potential falling object zone unaware, "
        "clear intervention point before material release. Wide shot captures ground loading area, "
        "vertical lift path, wind indicators, inadequate securing, and ground personnel positions. "
        "Overcast day with visible wind effects, construction tower, realistic material handling showing "
        "detectable weather violations before material becomes airborne."
    ),
    # Scenario 17: Traffic Work Zone Without Barrier Protection (EARLY DETECTION)
    (
        "Wide angle shot from elevated traffic camera position showing two-lane roadway and construction "
        "work zone. Camera captures 200-foot road section including travel lanes, shoulder area, and "
        "active work zone like standard traffic monitoring system. Scene reveals TRAFFIC CONTROL "
        "DEFICIENCIES: construction crew performing utility work in excavated hole 3 feet deep in right "
        "lane and shoulder area, single orange construction sign positioned 100 feet before work zone "
        "(requires advance warning at 500+ feet), no speed reduction warning signs visible, no flag "
        "person stationed to control traffic flow, no physical barrier separation between work area and "
        "live traffic lane - only plastic cones forming single line barrier with 5-foot gaps between "
        "cones, no crash attenuator truck or impact protection vehicle positioned before work zone. "
        "Camera shows BEFORE INCIDENT INDICATORS: three workers in high-visibility vests working in "
        "excavation with backs to oncoming traffic focused on underground pipe repair, traffic flowing "
        "in adjacent lane at highway speed (55 mph speed limit signs visible, no reduction posted), "
        "construction equipment including excavator positioned at excavation edge with boom extended over "
        "live lane reducing clearance, no advance lane closure or merge warning for approaching vehicles. "
        "CONVERGENCE OF HAZARDS: passenger vehicle approaching work zone at full speed, driver visible "
        "through windshield looking down at phone not at road ahead, vehicle in right travel lane (work "
        "zone lane) not merging left, workers in excavation completely unaware of approaching vehicle, "
        "gap in cone line at 40 feet before work area provides vehicle path directly into work zone, no "
        "rumble strips or road surface markings warning of work zone. Hold frame with vehicle 200 feet "
        "from work zone traveling 55 mph (3.6 seconds to impact) - intervention opportunity exists but "
        "narrowing. Wide shot shows inadequate traffic control, unprotected workers, vehicle approach "
        "vector, and systematic barrier failures. Daylight roadway conditions, realistic highway work "
        "zone showing detectable traffic safety violations before vehicle incursion."
    ),
    # Scenario 18: Damaged Power Tool Continued Use (EARLY DETECTION)
    (
        "Medium shot from workshop bench level showing carpentry work area from 12 feet away. Camera "
        "angle captures workbench surface, wall-mounted tool board, and worker position like standard "
        "shop safety camera. Scene opens with DETECTABLE TOOL SAFETY VIOLATIONS: circular saw positioned "
        "on workbench with visible damage - lower blade guard broken off completely exposing bottom half "
        "of blade teeth, power cord showing outer jacket damage with exposed wiring visible at 2-foot "
        "point from tool housing, sawdust buildup on tool body indicating continued use despite damage, "
        "manufacturer safety label partially torn off obscuring warning text. Camera shows SURROUNDING "
        "HAZARD INDICATORS: red electrical tag-out tags visible hanging on pegboard indicating damaged "
        "tools removed from service, but damaged saw sitting on active workbench not tagged, nearby "
        "properly functioning circular saw available on tool rack 8 feet away, inspection checklist on "
        "clipboard showing last power tool inspection 90 days prior (monthly required), no lockout "
        "device on damaged tool's trigger preventing use. BEFORE USE MOMENT: worker in safety glasses "
        "and hearing protection approaches workbench carrying wood plank to cut, worker picks up damaged "
        "circular saw examining it briefly but proceeding to plug cord into power strip, no hesitation "
        "visible despite obvious guard damage, worker positions plank on bench and places saw blade at "
        "cut line, finger moves toward trigger switch preparing to activate. CRITICAL WARNING SIGNS "
        "VISIBLE: exposed blade guard mounting points show broken plastic indicating forceful damage not "
        "gradual wear, damaged cord section positioned where worker's forearm will rest during cut "
        "creating shock exposure, no push stick or proper blade guards present for safe operation, wood "
        "plank contains visible knots that could cause blade binding and kickback. Hold frame with finger "
        "on trigger before activation - intervention point clear. Medium shot shows tool damage details, "
        "available alternatives, and unsafe procedure beginning. Workshop interior, fluorescent lighting, "
        "realistic damaged tool scenario showing detectable equipment violations before operation."
    ),
    # Scenario 19: Disconnected Fall Protection Lifeline (EARLY DETECTION)
    (
        "Wide shot from ground level 50 feet away showing steel framework of building under construction "
        "with workers on elevated beams. Camera angle captures three-story steel structure, installed "
        "beams, and fall protection system like job site safety monitoring. Scene reveals FALL PROTECTION "
        "VIOLATIONS: horizontal lifeline cable installed along beam run at 25-foot elevation, three "
        "workers wearing full-body harnesses with rear D-rings visible, but camera clearly shows CRITICAL "
        "DEFICIENCY - middle section of lifeline cable disconnected at turnbuckle connection point with "
        "6-inch gap between cable ends visible, disconnection point positioned between two workers "
        "creating unprotected zone. Camera captures ADDITIONAL DETECTABLE HAZARDS: worker in red hard "
        "hat currently connected to lifeline on left side of disconnection, second worker in blue hard "
        "hat on right side of disconnection with lanyard connected to compromised cable section - if red "
        "hat worker falls, system shock load will disconnect blue hat worker's lifeline, third worker in "
        "yellow hard hat approaching from right side preparing to connect to same compromised cable "
        "section unaware of disconnection, no fall protection monitoring or competent person visible on "
        "ground checking system integrity, lifeline system shows no load indicator or tension gauge to "
        "verify proper installation, beam surface wet from morning dew creating slip hazard. BEFORE "
        "INCIDENT MOMENT: blue hat worker walks outboard on beam toward disconnection point (currently "
        "12 feet from gap), worker's lanyard shock absorber pack visible but connected to cable section "
        "that terminates at gap - no continuous fall arrest protection, worker carries heavy beam "
        "connector plate affecting balance, slight breeze causing worker to adjust footing. Hold frame "
        "showing worker approaching compromised lifeline section - intervention window exists before "
        "critical position reached. Wide shot captures building frame, elevation height, lifeline "
        "discontinuity, and multiple worker positions relative to system failure point. Natural daylight, "
        "steel construction site, realistic fall protection showing detectable system deficiency before "
        "worker exposes self to unprotected fall hazard."
    ),
    # Scenario 20: Worker Too Close to Excavation Edge Collapse (EARLY DETECTION)
    (
        "Wide elevated shot from excavator operator cab perspective showing open excavation and edge "
        "conditions. Camera positioned 15 feet above ground capturing 50-foot excavation length, depth, "
        "and perimeter zone like equipment operator safety view. Scene reveals EXCAVATION SAFETY "
        "VIOLATIONS: trench 10 feet deep and 12 feet wide excavated in sandy soil, spoil pile located "
        "only 18 inches from excavation edge creating surcharge load (requires 2+ foot setback minimum), "
        "no edge protection barriers or warning fencing preventing access to edge zone, no caution tape "
        "marking danger area, excavation edge showing vertical cut with no benching or sloping despite "
        "unstable soil type. Camera shows DETECTABLE SOIL INSTABILITY INDICATORS: visible cracks running "
        "parallel to excavation edge at 3-foot distance from lip extending 20 feet along trench, small "
        "soil chunks continuously breaking off edge and falling into excavation, edge material sloughing "
        "creating undercut profile, recent rain evidenced by wet soil surfaces and puddles reducing soil "
        "cohesion, no protective ground mats or load distribution plates near edge. BEFORE COLLAPSE "
        "MOMENT: survey worker in orange vest and white hard hat standing at edge operating survey "
        "equipment on tripod positioned only 2 feet from excavation lip within crack pattern zone, "
        "worker's attention focused on survey instrument eyepiece not ground conditions, weighted "
        "equipment bag hanging on tripod leg adding 40 pounds point load to unstable edge area, second "
        "worker visible at trench bottom 10 feet below directly under edge section showing cracks - "
        "exposed to potential cave-in, no ladder or exit means visible within 25-foot lateral distance "
        "violating egress requirements. CRITICAL WARNING: camera shows edge crack propagating with small "
        "pebbles rolling into widening gap, surveyor shifts weight on tripod causing visible ground "
        "deflection at edge, spoil pile beginning to slump toward excavation. Hold frame showing worker "
        "on unstable edge, cracking soil, worker below in collapse zone - clear intervention point "
        "before edge failure. Wide elevated shot captures excavation depth, edge instability indicators, "
        "improper spoil placement, and personnel positions in hazard zones. Natural overcast light, "
        "active excavation site, realistic soil failure showing detectable cave-in precursors."
    ),
    # Scenario 21: Demolition Unsupported Structural Wall (EARLY DETECTION)
    (
        "Wide shot from 60 feet away at ground level showing interior demolition of commercial building. "
        "Camera captures partial building cross-section with structural elements and demo work like "
        "project documentation camera. Scene opens revealing STRUCTURAL HAZARDS: two-story masonry wall "
        "section remaining standing after adjacent roof structure removed, wall now acting as unsupported "
        "cantilever with no lateral bracing, visible mortar deterioration and brick face spalling, "
        "demolition debris piled at wall base creating unstable footing and impact vibration source. "
        "Camera shows DETECTABLE BEFORE COLLAPSE INDICATORS: vertical crack developing in brick wall at "
        "second floor level extending 8 feet from top to midpoint, wall showing visible lean of 4-5 "
        "degrees outward from plumb (detectable by comparing to nearby vertical references), temporary "
        "wood braces that were installed now removed and laying on ground indicating demolition sequence "
        "violation, engineered demolition plan clipboard visible on foreman desk in foreground showing "
        "wall section marked for controlled demolition after bracing installation (procedure not "
        "followed). HAZARDOUS SCENARIO DEVELOPING: worker in white hard hat operating skid steer loader "
        "with bucket attachment approaching wall base to remove debris pile, vibration from equipment "
        "engine and movement causing visible wall tremor, worker's trajectory puts equipment cab directly "
        "adjacent to wall base in collapse shadow zone, no exclusion zone barriers set up around "
        "unstable wall, second worker on foot visible 20 feet from wall carrying sledgehammer preparing "
        "to manually demolish lower section - procedure that will further destabilize upper wall. Camera "
        "clearly captures WARNING SIGNS: wall crack opening wider with small brick chips falling, dust "
        "puffing from mortar joints indicating movement, skid steer 10 feet from wall base and closing, "
        "no spotter or safety monitor watching wall stability. Hold moment before equipment reaches wall "
        "base - intervention opportunity exists. Wide shot shows unsupported wall height, structural "
        "instability, equipment approach, and procedural violations. Interior demolition site, dust in "
        "air, natural light through missing roof, realistic demo showing detectable collapse precursors."
    ),
    # Scenario 22: Material Hoist Overloaded Platform (EARLY DETECTION)
    (
        "Wide angle shot from second floor window looking down at construction material hoist ground "
        "loading area. Camera positioned 20 feet elevated capturing hoist platform, loading zone, and "
        "operator position like supervisor safety view. Scene reveals LOAD SAFETY VIOLATIONS: vertical "
        "construction hoist with 4x6 foot platform at ground level, manufacturer capacity placard on "
        "frame clearly visible stating '2000 LBS MAX LOAD', platform currently loaded with pallet of "
        "concrete blocks visible by distinctive gray masonry units, second pallet of blocks being "
        "positioned onto platform by forklift creating double stack, digital scale visible in corner of "
        "frame reads '2,400 LBS' indicating overload, no load calculation sheet or weight verification "
        "in operator's hands. Camera shows DETECTABLE HAZARDS BEFORE LIFT: platform deck flexing downward "
        "under weight with visible bow at center, hoist cable showing increased tension with cable "
        "strands slightly spread (normal cable shows tight strand grouping), platform safety gate not "
        "fully latched due to load volume preventing closure, load extends 10 inches beyond platform "
        "edge on one side unsecured, forklift operator in yellow vest preparing to retract forks and "
        "clear area signaling hoist operator to lift. ADDITIONAL WARNING SIGNS: hoist motor housing "
        "showing oil streak indicating hydraulic stress or maintenance issue, hoist maintenance log "
        "hanging on nearby post showing last inspection 6 months prior (monthly required), hoist "
        "operator in blue hard hat has hand on control lever ready to activate but operator position "
        "doesn't allow direct view of platform overload - vision blocked by nearby material stack, no "
        "load spotter or signal person at platform verifying safe loading. CRITICAL MOMENT: operator "
        "begins activation sequence with platform rising 6 inches - cable tension visible increasing, "
        "overloaded platform continues upward slowly showing structural strain. Hold frame at 2-foot "
        "elevation showing overload condition, compromised safety gate, unstable load - intervention "
        "point before critical height reached. Wide shot captures platform overload, weight documentation, "
        "operator position, and equipment strain indicators. Construction site loading area, natural "
        "daylight, realistic material hoist showing detectable capacity violations before mechanical "
        "failure or load release."
    ),
    # Scenario 23: Electrical Panel Exposed Live Bus Bars (EARLY DETECTION)
    (
        "Medium shot from 10 feet away showing temporary construction electrical distribution panel. "
        "Camera angle captures full panel front, surrounding area, and approaching worker like facility "
        "maintenance camera. Scene opens with ELECTRICAL HAZARDS VISIBLE: gray 400-amp temporary power "
        "panel mounted on wooden post, panel cover door standing completely open exposing interior "
        "components, camera clearly shows copper bus bars energized with visible electrical glow/shimmer, "
        "main disconnect switch in ON position with indicator lights illuminated confirming live power, "
        "multiple circuit breakers with connected conductors visible inside panel. Camera reveals "
        "DETECTABLE VIOLATIONS: no warning barriers or caution tape around panel creating restricted "
        "access zone, electrical hazard warning labels present but ineffective with open panel, no "
        "lockout tagout device on panel despite open condition requiring service, missing panel cover "
        "screws visible on ground indicating cover removed and not temporarily opened, no insulated "
        "rubber matting at panel base for worker protection, nearby work area with metal scaffolding "
        "only 6 feet from exposed panel creating conductive path hazard. BEFORE INCIDENT SCENARIO: "
        "worker in green coveralls and hard hat (no electrical safety rating visible on helmet) walking "
        "toward panel carrying metal conduit pipe on shoulder, worker's trajectory direct toward open "
        "panel, worker's attention on talking with coworker 15 feet away not watching path ahead, no "
        "qualified electrical person present in area, no hot work permit or electrical safety plan "
        "visible posted. CONVERGING HAZARDS: worker now 8 feet from panel still carrying 10-foot metal "
        "conduit that will pass within 2 feet of exposed bus bars based on current angle, wet ground "
        "conditions from recent rain visible with puddles creating conductive path to earth, worker's "
        "rubber boot soles showing metal toe caps (conductive), light breeze causing untethered "
        "electrical conductors inside panel to sway. Hold frame showing worker approaching with "
        "conductive material, exposed energized components, wet conditions - clear intervention window "
        "before electrical contact. Medium shot captures panel interior hazards, worker approach path, "
        "environmental factors, and safety violation stack. Construction site, natural overcast light, "
        "realistic electrical installation showing detectable shock/arc flash hazards before contact."
    ),
    # Scenario 24: Spilled Hydraulic Fluid Creating Slip Hazard (EARLY DETECTION)
    (
        "Wide shot from elevated camera position showing equipment maintenance area of construction site. "
        "Camera captures 40-foot zone including parked equipment, maintenance bay, and foot traffic paths "
        "like facility safety monitoring. Scene reveals ENVIRONMENTAL HAZARD: hydraulic excavator parked "
        "in maintenance area with visible fluid leak from hydraulic cylinder fitting creating expanding "
        "puddle on concrete surface, puddle approximately 4 feet in diameter of dark hydraulic oil "
        "showing rainbow sheen surface characteristic of petroleum products, leak actively dripping at "
        "rate of one drop per second indicating pressurized system still containing residual pressure. "
        "Camera shows DETECTABLE SAFETY DEFICIENCIES: no absorbent materials or spill containment booms "
        "deployed around leak despite hazard mat storage cabinet visible 20 feet away, no caution cones "
        "or wet floor warning signs positioned around contaminated area, no caution tape establishing "
        "barrier preventing foot traffic through spill zone, main walking path from job site trailer to "
        "equipment yard passes directly through contaminated area with visible foot traffic use patterns "
        "(dusty footprints on clean concrete nearby), spill report forms visible on maintenance board but "
        "no documentation hanging on excavator indicating leak reported. BEFORE INCIDENT MOMENT: worker "
        "in brown boots and blue coveralls walking from trailer toward equipment yard carrying laptop "
        "and morning coffee cup, worker's attention on laptop screen reading emails while walking, "
        "worker's path trajectory places next footstep at edge of hydraulic fluid puddle in 3-4 steps, "
        "worker wearing standard leather work boots with no slip-resistant tread visible, smooth concrete "
        "surface showing no texture or grip features, slight grade slope causing fluid to spread toward "
        "walking path. CONVERGING FACTORS: second worker visible behind approaching from opposite "
        "direction also not watching ground, morning sunlight creating glare on wet concrete reducing "
        "fluid visibility, maintenance supervisor visible in background on phone call not watching work "
        "area. Hold frame with lead worker 8 feet from contact with contaminated surface - intervention "
        "opportunity present. Wide shot shows spill size and spread, walking path intersection, multiple "
        "approaching personnel, and absent containment measures. Construction maintenance area, morning "
        "natural light, realistic fluid leak showing detectable slip hazard before pedestrian contact."
    ),
    # Scenario 25: Overhead Work Tools Left on Platform Edge (EARLY DETECTION)
    (
        "Wide shot from ground level looking up at multi-level scaffolding structure from 30 feet away. "
        "Camera positioned to capture scaffolding levels, workers, and ground area below like job site "
        "safety documentation view. Scene reveals FALLING OBJECT HAZARDS: tube and coupler scaffolding "
        "erected to three levels (30 feet height), workers on top platform performing facade repair work, "
        "multiple tools visible positioned at platform edge including hammer, pry bar, and adjustable "
        "wrench within 6 inches of platform perimeter, no tool tethering or lanyards visible connecting "
        "tools to structure or workers, platform lacks toe boards along edge (required 4-inch minimum "
        "board preventing tool rolloff), scaffold perimeter guardrail installed but tool storage creates "
        "hazard. Camera shows DETECTABLE VIOLATIONS BEFORE INCIDENT: red metal toolbox on platform with "
        "lid open and tools scattered across deck rather than secured storage, power drill sitting loose "
        "on platform plank 4 inches from edge with bit installed (potential puncture hazard if falling), "
        "open-end wrench positioned half-off platform edge showing clear fall potential, no debris netting "
        "or catch platform installed below work area despite overhead work activity, no barricade or "
        "exclusion zone on ground below scaffold creating safe perimeter. GROUND LEVEL HAZARDS: three "
        "workers on ground level moving materials underneath scaffold structure completely unaware of "
        "overhead falling object risk, workers not wearing hard hats despite overhead work (visible heads "
        "with no protection), material staging area established directly below work platform violating "
        "safe procedures, electrical conduit bundle being carried by two ground workers passes under "
        "scaffold with workers looking at each other coordinating movement not watching overhead. "
        "CRITICAL MOMENT: worker on top platform (30 feet up) reaches for different tool causing platform "
        "deck boards to flex visibly, flex motion causes adjustable wrench at edge to begin rolling "
        "toward drop zone, worker's boot steps backward toward tool creating kick hazard. Hold frame "
        "showing tool at platform edge beginning to fall, ground workers positioned in impact zone "
        "12 feet below edge, no protective systems - intervention window exists. Wide shot captures "
        "vertical height, tool positions at edges, unprotected ground workers, and absent protective "
        "measures. Construction site, natural daylight, realistic scaffolding work showing detectable "
        "falling object hazards before tool release."
    ),
]


def get_all_prompts() -> list[str]:
    return CONSTRUCTION_SAFETY_PROMPTS
